In [2]:
def addX(_x) :
    return x + _x
x = 10
y = 20
res = addX(y)
print(res)

30


In [5]:
def addX(_x) :
    global x
    x = x + _x # 에러 발생
    
x = 10
y = 20
addX(y)
print(x)

30


In [5]:
def hour_min_sec(s):
    h = s//3600
    m = (s%3600)//60
    s = (s%3600)%60
    return h,m,s

h,m,s = hour_min_sec(10007)
print(h,m,s)

2 46 47


In [2]:
import numpy as np

In [9]:
np.array([[1,2],[3,4]], dtype=complex)

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [12]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [15]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [17]:
np.arange( 0, 2, 9 )

array([0])

In [18]:
a = np.arange(6)

In [19]:
print(a)

[0 1 2 3 4 5]


In [20]:
b = np.arange(12).reshape(4,3)

In [21]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
c = np.arange(24).reshape(2,3,4)

In [26]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [29]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [3]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [33]:
import sys

In [37]:
np.set_printoptions(threshold=sys.maxsize)

In [5]:
print(sys.maxsize)

In [12]:
x = np.arange(10)

In [13]:
x[2]

2

In [14]:
x[-2]

8

In [17]:
x.shape = (2,5)

In [19]:
x[1,3]

8

In [20]:
x[1,-1]

9

In [21]:
x[0]

array([0, 1, 2, 3, 4])

In [23]:
x[1][-1]

9

In [24]:
a = np.array(range(1,10)).reshape(3,3)

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a[[0,1,2,0],[0,2,0,1]]

array([1, 6, 7, 2])

In [27]:
x = np.arange(10)

In [28]:
x[2:5]

array([2, 3, 4])

In [29]:
x[:-7]

array([0, 1, 2])

In [30]:
x[1:7:2]

array([1, 3, 5])

In [36]:
y = np.arange(35).reshape(5,7)

In [32]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [42]:
a = np.array(range(6)).reshape(2,3)

In [41]:
bool_idx = a > 2
print(bool_idx)

[[False False False]
 [ True  True  True]]


In [45]:
a[bool_idx]
# a[a>2]

array([3, 4, 5])

In [46]:
~bool_idx

array([[ True,  True,  True],
       [False, False, False]])

In [47]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [49]:
b = a[:2]

In [50]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
c = a[:,1:3]

In [52]:
c

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [53]:
d = a[:,1]

In [54]:
d

array([ 2,  6, 10])

In [57]:
b[0,0] = -100

In [59]:
print(b)

[[-100    2    3    4]
 [   5    6    7    8]]


In [60]:
print(a)
#numpy에서 : 슬라이싱하여 쓸 경우 주소를 share하기 때문에 a 값도 변경되었다.

[[-100    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]


In [62]:
np.shares_memory(a,b)
# a와b가 같은 메모리를 공유하고 있다.

True

In [63]:
b = np.copy(a[:2])
# copy함수를 사용하면 주소를 share하지 않는다.

In [66]:
b[0,0] = 9999

In [78]:
a

array([[-100,    2,    3,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

In [79]:
b

array([[9999,    2,    3,    4],
       [   5,    6,    7,    8]])

In [80]:
# numpy에서는 주소를 공유하는지 shares_memory함수를 통해서 알수있고 id함수를 통해서 어느 메모리에 위치하는지 확인하는 것은 불가능

In [84]:
np.shares_memory(a,b)

False

In [85]:
a = np.floor(10*np.random.random((3,4)))#numpy안의 random안에 random이라는 함수를 사용하겠다.

In [86]:
a

array([[4., 4., 5., 6.],
       [6., 5., 2., 0.],
       [8., 2., 9., 8.]])

In [87]:
a.shape

(3, 4)

In [88]:
a.ravel() #

array([4., 4., 5., 6., 6., 5., 2., 0., 8., 2., 9., 8.])

In [89]:
a.reshape(6,2)

array([[4., 4.],
       [5., 6.],
       [6., 5.],
       [2., 0.],
       [8., 2.],
       [9., 8.]])

In [90]:
a.T # 트랜스포즈 함수(전치행렬)

array([[4., 6., 8.],
       [4., 5., 2.],
       [5., 2., 9.],
       [6., 0., 8.]])

In [92]:
a.T.shape

(4, 3)

In [93]:
a.resize((2,6)) #

In [94]:
a

array([[4., 4., 5., 6., 6., 5.],
       [2., 0., 8., 2., 9., 8.]])

In [125]:
a.reshape(3,-1) #-1을 주면 남은 숫자를 알아서 계산

array([[0, 1],
       [2, 3],
       [4, 5]])

In [126]:
a = np.array(range(6)).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [127]:
np.reshape(a,(3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [128]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [129]:
a.resize(3,2)

In [130]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [117]:
a = np.array(range(6)).reshape(2,3)
b = np.array(range(10,16)).reshape(2,3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]


In [119]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [120]:
np.hstack((a,b))

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [132]:
a = np.floor(10*np.random.random((3,4))).reshape(2,6)
a

array([[2., 3., 0., 3., 6., 9.],
       [1., 4., 1., 7., 7., 1.]])

In [133]:
np.hsplit(a,3)

[array([[2., 3.],
        [1., 4.]]),
 array([[0., 3.],
        [1., 7.]]),
 array([[6., 9.],
        [7., 1.]])]

In [156]:
whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    5x5: 25 elems, type `float64`, 200 bytes
b          ndarray    5x5: 25 elems, type `bool`, 25 bytes
bool_idx   ndarray    2x3: 6 elems, type `bool`, 6 bytes
c          ndarray    3x2: 6 elems, type `int64`, 48 bytes
d          ndarray    3: 3 elems, type `int64`, 24 bytes
np         module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
x          ndarray    10: 10 elems, type `int64`, 80 bytes
y          ndarray    5x7: 35 elems, type `int64`, 280 bytes
z          ndarray    5x5: 25 elems, type `float64`, 200 bytes


### 실습 문제1

In [192]:
a = np.ones((5,5))
print("Original array:")
print(a)
print("1 on the border and 0 inside in the array:")
a[1:-1,1:-1] = 0
print(a)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [154]:
z = np.zeros((5,5))
z[1:-1,1:-1] = 1
print(z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [163]:
x = np.ones((3,3))
x = np.pad(x, pad_width=1)

In [165]:
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 실습 문제2

In [200]:
x = np.ones((8,8), dtype=int)
x[0::2,::2] = 0
x[1::2,1::2] = 0
print("checkerboard pattern :")
print(x)

checkerboard pattern :
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 실습 문제3

In [203]:
data = np.array([180,72,172,66,162,60,167,53,176,80,155,60,177,77,130,40])
print(data)
batch = data.reshape(2,4,2)
print(batch)

[180  72 172  66 162  60 167  53 176  80 155  60 177  77 130  40]
[[[180  72]
  [172  66]
  [162  60]
  [167  53]]

 [[176  80]
  [155  60]
  [177  77]
  [130  40]]]


In [204]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [205]:
print(x+y)

[[ 6  8]
 [10 12]]


In [206]:
print(x-y)

[[-4 -4]
 [-4 -4]]


In [207]:
print(x*y)

[[ 5 12]
 [21 32]]


In [208]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [209]:
a = np.array([20,30,40,50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [210]:
c = a-b

In [211]:
c

array([20, 29, 38, 47])

In [212]:
b**2

array([0, 1, 4, 9])

In [213]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [214]:
a<35

array([ True,  True, False, False])

In [215]:
# *는 elementwise로 동작
# @ 행렬곱, dot 행렬곱

In [216]:
a @ b

260

In [217]:
a.dot(b)

260

In [218]:
a.sum()

140

In [219]:
a.min()

20

In [220]:
a.max()

50

In [232]:
b = np.arange(12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [233]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [238]:
b.min(axis=1)

array([0, 4, 8])

In [239]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [240]:
type(np.reshape)

function

In [241]:
type(a.reshape)

builtin_function_or_method

In [249]:
x = np.array(range(1,13)).reshape(4,3)
print(x, end='\n\n')
v = np.array([1,0,1])
print(y, end='\n\n')
y = np.empty_like(x)

for i in range(len(x)):
    y[i,:] = x[i,:] + v

print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [265]:
x = np.array(range(1,13)).reshape(4,3)
print(x, end='\n\n')
v = np.array([1,0,1])
print(y, end='\n\n')
v = np.tile(v,(4,1))
y = x + v
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [251]:
x = np.array(range(1,13)).reshape(4,3)
print(x, end='\n\n')
v = np.array([1,0,1])
print(v, end='\n\n')
y = x + v

print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [257]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[4,5],[7,8]])

In [258]:
print(np.concatenate((a,b),axis=1))

[[1 2 3 4 5]
 [4 5 6 7 8]]


In [260]:
a = np.array([1,2,3])

array([[1, 2, 3],
       [4, 5, 6]])

In [261]:
print(a.shape)

(2, 3)


In [262]:
np.expand_dims(a,2).shape

(2, 3, 1)

In [278]:
data = np.random.random((4,6)).round(1)
print(data, end='\n\n')
length = np.array([4,1,6,3])
print(length.shape, end='\n\n')
length = np.expand_dims(length, 1)
print(length.shape)

[[0.9 0.6 0.  0.7 0.3 0.8]
 [0.5 0.8 1.  0.7 0.2 0.5]
 [0.3 0.2 0.8 0.8 1.  0.5]
 [0.3 0.4 0.4 0.9 1.  0.1]]

(4,)

(4, 1)


In [279]:
maxlen = data.shape[1]
idx = np.arange(maxlen)
idx = np.tile(idx, (4,1))
print(idx, end='\n\n')
mask = idx < length
print(mask, end='\n\n')
data[~mask] = float('inf')
print(data)

[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]

[[ True  True  True  True False False]
 [ True False False False False False]
 [ True  True  True  True  True  True]
 [ True  True  True False False False]]

[[0.9 0.6 0.  0.7 inf inf]
 [0.5 inf inf inf inf inf]
 [0.3 0.2 0.8 0.8 1.  0.5]
 [0.3 0.4 0.4 inf inf inf]]
