In [1]:
import torch
import torch.nn

In [2]:
vocab = {
    'POSCO': 0,
    'AI': 1,
    '전문가': 2,
    'NLP': 3,
    '인공지능': 4,
    'embedding': 5,
    '실습': 6
}

In [3]:
dim=10
emb_mtx = torch.nn.Embedding(len(vocab), dim)

In [4]:
print(emb_mtx) # 7개단어를 10차원으로 표현

Embedding(7, 10)


In [5]:
print(emb_mtx.weight) # 초기의 random initial vector

Parameter containing:
tensor([[-2.4858,  0.9033, -1.0270, -0.5331, -0.7644, -0.4425,  0.8542, -1.1598,
         -1.1363, -2.0623],
        [-1.2566, -1.3067, -1.5555, -0.1358, -0.9914, -0.6646,  1.1866,  1.1192,
         -0.4792,  1.2220],
        [-0.8525,  2.0618,  0.2329, -0.2943, -0.3341,  0.5243,  0.1683,  0.4665,
         -1.1248,  0.6217],
        [-0.2990,  0.1780,  0.8121, -0.1363, -0.2948, -0.4653,  0.7709,  0.5960,
         -1.2717, -0.6549],
        [-0.4411, -0.1991, -0.1730,  0.4046, -1.2239, -0.5678,  0.5738,  0.8541,
          0.2485,  0.0894],
        [-0.6940,  0.4135, -0.4881,  0.3809,  0.8480,  0.1803, -1.3119,  0.1666,
          0.6555,  0.1669],
        [-0.3912,  0.1168,  0.5105, -0.1133, -0.0096,  1.2927, -0.4495, -0.1373,
         -0.9209, -0.2353]], requires_grad=True)


# Problem 1
Print the word embedding of 'POSCO'

In [6]:
idx = torch.tensor(vocab['POSCO'], dtype=torch.long) # make an index tensor for 'POSCO' (hint: the tensor's dtype is torch.long)
# feed the index tensor to emb_mtx
emb = emb_mtx(idx)

In [7]:
print(idx, idx.size())

tensor(0) torch.Size([])


In [8]:
print(emb, emb.size())

tensor([-2.4858,  0.9033, -1.0270, -0.5331, -0.7644, -0.4425,  0.8542, -1.1598,
        -1.1363, -2.0623], grad_fn=<EmbeddingBackward>) torch.Size([10])


# Problem 2
Print the embeddings of the words in the sentence "POSCO AI 전문가"

In [12]:
sent = ['POSCO', 'AI', '전문가']
idxs = []

for word in sent:
    idx = vocab[word] # convert a word into an index
    # append idx to idxs
    idxs.append(idx)

idxs = torch.tensor(idxs, dtype=torch.long) # convert the indices to a tensor
emb = emb_mtx(idxs) # matrix는 함수의 형태 # convert the indices into word embeddings

In [13]:
print(idxs, idxs.size())

tensor([0, 1, 2]) torch.Size([3])


In [14]:
print(emb, emb.size())

tensor([[-2.4858,  0.9033, -1.0270, -0.5331, -0.7644, -0.4425,  0.8542, -1.1598,
         -1.1363, -2.0623],
        [-1.2566, -1.3067, -1.5555, -0.1358, -0.9914, -0.6646,  1.1866,  1.1192,
         -0.4792,  1.2220],
        [-0.8525,  2.0618,  0.2329, -0.2943, -0.3341,  0.5243,  0.1683,  0.4665,
         -1.1248,  0.6217]], grad_fn=<EmbeddingBackward>) torch.Size([3, 10])


# Problem 3
Construct batch-level word embeddings for

```python
["POSCO AI 전문가", "NLP embedding 실습"]
```

In [15]:
batch = [['POSCO', 'AI', '전문가'],
         ['NLP', 'embedding', '실습']]
batch_idxs = []

for sent in batch:
    idxs = []
    for word in sent:
        idx = vocab[word] # convert a word into an index
        # append idx to idxs
        idxs.append(idx)
        # append idxs to batch_idxs
    batch_idxs.append(idxs)

batch_idxs = torch.tensor(batch_idxs, dtype=torch.long) # convert batch_idxs into a tensor
emb = emb_mtx(batch_idxs) # convert idxs into word embedding

In [16]:
print(batch_idxs, batch_idxs.size())

tensor([[0, 1, 2],
        [3, 5, 6]]) torch.Size([2, 3])


In [17]:
print(emb, emb.size())

tensor([[[-2.4858,  0.9033, -1.0270, -0.5331, -0.7644, -0.4425,  0.8542,
          -1.1598, -1.1363, -2.0623],
         [-1.2566, -1.3067, -1.5555, -0.1358, -0.9914, -0.6646,  1.1866,
           1.1192, -0.4792,  1.2220],
         [-0.8525,  2.0618,  0.2329, -0.2943, -0.3341,  0.5243,  0.1683,
           0.4665, -1.1248,  0.6217]],

        [[-0.2990,  0.1780,  0.8121, -0.1363, -0.2948, -0.4653,  0.7709,
           0.5960, -1.2717, -0.6549],
         [-0.6940,  0.4135, -0.4881,  0.3809,  0.8480,  0.1803, -1.3119,
           0.1666,  0.6555,  0.1669],
         [-0.3912,  0.1168,  0.5105, -0.1133, -0.0096,  1.2927, -0.4495,
          -0.1373, -0.9209, -0.2353]]], grad_fn=<EmbeddingBackward>) torch.Size([2, 3, 10])
