# Lecture1; Tutorial

### Check your Tensorflow version

In [1]:
import tensorflow as tf
print(tf.__version__)

2.2.0


### Tensor

In [2]:
t = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
tensor = tf.constant(t)

print(tensor)
print()
print("shape :", tf.shape(tensor))
print("size :", tf.size(tensor))
print("rank :", tf.rank(tensor))

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int32)

shape : tf.Tensor([12], shape=(1,), dtype=int32)
size : tf.Tensor(12, shape=(), dtype=int32)
rank : tf.Tensor(1, shape=(), dtype=int32)


In [3]:
def print_ssr(tensor):
    print(tensor)
    print()
    print("shape :", tf.shape(tensor))
    print("size :", tf.size(tensor))
    print("rank :", tf.rank(tensor))

In [4]:
hd = tf.reshape(tensor, [1, 2, 1, 3, 1, 2, 1])
print(tf.squeeze(hd, [0,2,4]).shape)

(2, 3, 2, 1)


In [5]:
tensor2d = tf.reshape(tensor, [3,4])
# tensor2d = tensor.reshape([3,4]) : 오류(pytorch)

print_ssr(tensor2d)
#shape = 각각의 차원에서 차원의 크기
#size = tensor의 원소가 몇개인지
#rank = 차원의 크기

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)

shape : tf.Tensor([3 4], shape=(2,), dtype=int32)
size : tf.Tensor(12, shape=(), dtype=int32)
rank : tf.Tensor(2, shape=(), dtype=int32)


In [9]:
print(tensor2d[1]) #print(tensor2d[1,:])
print(tensor2d[1,2])

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [10]:
tensor3d = tf.reshape(tensor, [3, 2, 2])
print_ssr(tensor3d)

tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], shape=(3, 2, 2), dtype=int32)

shape : tf.Tensor([3 2 2], shape=(3,), dtype=int32)
size : tf.Tensor(12, shape=(), dtype=int32)
rank : tf.Tensor(3, shape=(), dtype=int32)


In [11]:
tensor3d = tf.reshape(tensor, [3, 1, 4])
print_ssr(tensor3d)

tf.Tensor(
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]], shape=(3, 1, 4), dtype=int32)

shape : tf.Tensor([3 1 4], shape=(3,), dtype=int32)
size : tf.Tensor(12, shape=(), dtype=int32)
rank : tf.Tensor(3, shape=(), dtype=int32)


In [12]:
tensor3d = tf.reshape(tensor, [1, 3, 4])
print_ssr(tensor3d)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]], shape=(1, 3, 4), dtype=int32)

shape : tf.Tensor([1 3 4], shape=(3,), dtype=int32)
size : tf.Tensor(12, shape=(), dtype=int32)
rank : tf.Tensor(3, shape=(), dtype=int32)


In [14]:
x = tf.constant([1, 0, -1, 1])
print_ssr(x)

tf.Tensor([ 1  0 -1  1], shape=(4,), dtype=int32)

shape : tf.Tensor([4], shape=(1,), dtype=int32)
size : tf.Tensor(4, shape=(), dtype=int32)
rank : tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
#tf.matmul(tensor3d,x)   -> InvalidArgumentError

In [16]:
tensor3d = tf.squeeze(tensor3d)
print(tensor3d) # 1차원은 없애고 크기가 있는 차원만 남김

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [17]:
x = tf.expand_dims(x,1) # 확장하고 싶은 자리를 입력하면 차원이 확장됨 (rank가 1이면 1보다작은 0, 1중에서 넣어야함)
print(x)

tf.Tensor(
[[ 1]
 [ 0]
 [-1]
 [ 1]], shape=(4, 1), dtype=int32)


In [18]:
tf.matmul(tensor3d,x)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[ 2],
       [ 6],
       [10]], dtype=int32)>

In [19]:
print(tensor3d@x)

tf.Tensor(
[[ 2]
 [ 6]
 [10]], shape=(3, 1), dtype=int32)


In [20]:
mat = tf.constant([[1.0, 2.0],[3.0, 4.0]])

my_sum = tf.reduce_sum(mat) # 축에 대한 설정 없을경우 -> 행렬의 전체 합 =sum과 같다
my_mean = tf.reduce_mean(mat)
print(my_sum)
print(my_mean)

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor(2.5, shape=(), dtype=float32)


In [21]:
print(tf.reduce_mean(mat, 0)) # reduce_mean : 축을 설정해서 축에 맞게 계산
print(tf.reduce_mean(mat, 1))
print(tf.reduce_sum(mat, 0))
print(tf.reduce_sum(mat, 1))

tf.Tensor([2. 3.], shape=(2,), dtype=float32)
tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)
tf.Tensor([4. 6.], shape=(2,), dtype=float32)
tf.Tensor([3. 7.], shape=(2,), dtype=float32)


In [22]:
mat1 = tf.constant([[1.0, 2.0],[3.0, 4.0]])
mat2 = tf.Variable([[1.0, 2.0],[3.0, 4.0]])

print(mat1)
print(mat2)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>
