In [1]:
import tensorflow as tf
print(tf.__version__)

2.2.0


In [3]:
tf.executing_eagerly()
# Define by run 방식

True

In [4]:
t1 = tf.constant([[1.0, 2.0],[3.0, 4.0]])
print(t1)
print(type(t1))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [5]:
t1_np = t1.numpy()
print(t1_np)

[[1. 2.]
 [3. 4.]]


In [8]:
weight = tf.Variable(tf.random_normal_initializer(stddev=0.1)([5,2]))
print(weight)

<tf.Variable 'Variable:0' shape=(5, 2) dtype=float32, numpy=
array([[ 0.05394567, -0.03226994],
       [-0.0911716 ,  0.08809431],
       [-0.03919906, -0.04286901],
       [-0.00276217, -0.18832874],
       [ 0.14174081,  0.08939641]], dtype=float32)>


In [9]:
import timeit

# Create an oveerride model to classify pictures
class SequentialModel(tf.keras.Model):
    def __init__(self, **kwargs):
        super(SequentialModel, self).__init__(**kwargs)
        self.flatten = tf.keras.layers.Flatten(input_shape=(28, 28))
        self.dense_1 = tf.keras.layers.Dense(128, activation="relu")
        self.dropout = tf.keras.layers.Dropout(0.2)
        self.dense_2 = tf.keras.layers.Dense(10)

    def call(self, x):
        x = self.flatten(x)
        x = self.dense_1(x)
        x = self.dropout(x)
        x = self.dense_2(x)
        return x

input_data = tf.random.uniform([60, 28, 28])

eager_model = SequentialModel()
graph_model = tf.function(eager_model)

print("Eager time:", timeit.timeit(lambda: eager_model(input_data), number=50000))
print("Graph time:", timeit.timeit(lambda: graph_model(input_data), number=50000))

'''
graph 모델이 어디에나 다 좋지는 않다.
모델에서는 속도향상이 되고 for문에서는 차이가 크지않음
'''

Eager time: 39.46737035596743
Graph time: 14.370273206848651


In [11]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() # Tensorflow 2.x에서 하는 행동을 못하게막음
print(tf.__version__)

Instructions for updating:
non-resource variables are not supported in the long term
2.2.0


In [12]:
tf.reset_default_graph()

a = tf.constant(3.0)
b = tf.constant(4.0)
total = a + b

print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)
