# ◽️ Deep Learning Frameworks 
---
#### ✔️ Computational Graph
- Computational graph using Numpy

In [3]:
import numpy as np 
np.random.seed(0)

N, D = 3, 4

x = np.random.randn(N, D)
y = np.random.randn(N, D)
z = np.random.randn(N, D)

a = x * y
b = a + z
c = np.sum(b)

grad_c = 1.0

## TO DO : Manually calculate gradients
grad_b = grad_c*np.ones((N,D)) # Summation => copy
grad_a = grad_b.copy()
grad_z = grad_b.copy()
grad_x = grad_a*y
grad_y = grad_a*x
##
print(grad_y)

[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]]


- Computational graph using Tensorflow

In [4]:
import numpy as np
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

N, D = 3, 4

x = tf.compat.v1.placeholder(tf.float64)
y = tf.compat.v1.placeholder(tf.float64)
z = tf.compat.v1.placeholder(tf.float64)

a = x * y
b = a + z
c = tf.reduce_sum(b)
init = tf.compat.v1.global_variables_initializer()

grad_x, grad_y, grad_z = tf.gradients(c, [x, y, z])

with tf.compat.v1.Session() as sess:
    np.random.seed(0)
    values = {
        x: np.random.randn(N, D),
        y: np.random.randn(N, D),
        z: np.random.randn(N, D),
    }
    out = sess.run([c, grad_x, grad_y, grad_z], feed_dict=values)
    c_v, grad_x_v, grad_y_v, grad_z_v = out

- Computational graph using PyTorch

In [5]:
import torch

N, D = 3, 4

x = torch.randn(N, D, requires_grad=True)
y = torch.randn(N, D, requires_grad=True)
z = torch.randn(N, D, requires_grad=True)

a = x * y
b = a + z
c = torch.sum(b)

c.backward()

print(x.grad)

tensor([[-0.5772, -0.5710, -1.4200, -1.2423],
        [ 0.3827,  0.4864,  0.5087,  0.8591],
        [-0.4579,  0.0705, -0.4195, -1.4287]])
