# ◽️ Numpy Tutorial
> Indexing 과 broadcasting 복습
---

#### ✔️ Array indexing
* Numpy array의 indexing은 일반적인 list와 유사하다. 
* 단, indexing해서 분리한 array도 원래 array의 memory를 참조하기 때문에 변경할 때 유의하여야 한다.

In [1]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, '\n')

# [[2 3]
#  [6 7]]
# call-by-reference가 된 경우
b = a[:2, 1:3]
print(b)

print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[2 3]
 [6 7]]
2
77


#### ✔️ Slicing을 할 때는 dimension이 낮아질 수 있다.
- Slicing을 하는 방법에는 여러가지가 있는데, integer를 활용해 indexing을 할 때는 dimension이 낮아지고, slicing을 이용해 indexing 할 때는 dimension이 유지된다.

In [3]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, a.shape, '\n')

row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a, Array로 가져오면 Dimesion이 유지된다.
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
# row_r1 = np.expand_dims(row_r1, axis=0)
print("Slicing Row")
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)


col_r1 = a[:, 1] # integer로 가져오면 dimension이 없어짐
col_r2 = a[:, 1:2]
print("Slicing Column")
print(col_r1, col_r1.shape, '\n')
print(col_r2, col_r2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 

Slicing Row
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)
Slicing Column
[ 2  6 10] (3,) 

[[ 2]
 [ 6]
 [10]] (3, 1)


#### ✔️ Integer array를 이용해 indexing을 할 수 있다. 
- Slicing을 할 때는 네모난 subarray만 추출할 수 있지만, integer array를 이용할 경우 임의의 수치들을 꺼내올 수 있다.

In [4]:
a = np.array([[1,2], [3, 4], [5, 6]])

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))
print(a[[0, 1, 2], [0, 1, 0]])

[1 4 5]
[1 4 5]


In [10]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

index = np.array([0, 2, 0, 1])

## TODO
# Select one element from each row of 'a' using the indices
indexed = a[[0, 1, 2, 3], index]

# Select one element from each row of 'a' and increment them by 10
a[[0, 1, 2, 3], index] += 10
##

print(indexed) # should print "[1 6 7 11]"
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


- Boolean array로도 indexing을 할 수 있다. 

In [16]:
condition = a > 2
print(a > 2)

##TO DO : indexing emelements of 'a' with 'condition'
a_condition = a[condition]
#a_condition = a[a>2]
##

print(a_condition, a_condition.shape)

[[ True False  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[11  3  4  5 16 17  8  9 10 21 12] (11,)


#### ✔️ Broadcasting
- Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
- Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
- Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [17]:
'''
a -> [4] -> [1,4] # rule1 --> [3, 4] # rule3
b -> [3, 4]
a + b
'''

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   

for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
y = x + vv  
print(y)

y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


#### *Broadcasting Quiz*
* is `x+y` broadcastable for each case?

In [21]:
# case 1
x=np.empty((0))    # [0]   -> [1,0] -> [2,0] #shape이 0이기 때문에 계산안됨
y=np.empty((2,2))  # [2,2] -> [2,2] -> [2,2]
# False
        
# case 2
x=np.empty((5,3,4,1)) # [5, 3, 4, 1]  ->     [5, 3, 4, 1] ->     [5, 3, 4, 1]
y=np.empty((3,4,1))   # [3, 3, 1]     ->(R1) [1, 3, 4, 1] ->(R2) [5, 3, 4, 1]
# True

# case 3
x=np.empty((5,3,4,1)) # [5, 3, 4, 1]  ->     [5, 3, 4, 1] ->     [5, 3, 4, 1]
y=np.empty((3,1,1))   # [3, 1, 1]     ->(R1) [1, 3, 1, 1] ->(R2) [5, 3, 4, 1]
# True

# case 4
x=np.empty((5,2,4,1)) # [5, 2, 4, 1]  ->     [5, 2, 4, 1] ->     [5, 2, 4, 1]
y=np.empty((3,1,1))   # [3, 1, 1]     ->(R1) [1, 3, 1, 1] ->(R2) [5, 3, 4, 1]
# False

#### *지금까지 배운 indexing 과 Broadcasting 방법이 ***모두*** Pytorch에도 적용 된다.*