In [2]:
from IPython.display import clear_output
from tqdm import trange
import time

def vis(env):
        clear_output(wait=True)
        env.render()
        time.sleep(0.2)

In [3]:
import gym
import numpy as np

class Agent():
    def __init__(self):
        super(Agent, self).__init__()
        self.q_table = np.zeros((16,4))
        self.eps = 0.3
    def select_action(self,state):
        x = state
        max_action = np.argmax(self.q_table[x])
        random_action = np.random.randint(0,4)

        action = np.random.choice([max_action,random_action],p=[1-self.eps,self.eps])
        return action
    def play_episode(self,env):
        state = env.reset()
        while True:
            action = self.select_action(state)
            next_state, reward, done, info = env.step(action)

            x = state
            next_x = next_state

            agent.q_table[x, action] += alpha * (reward + (1-done)*gamma*np.max(agent.q_table[next_x]) - agent.q_table[x, action])

            state = next_state
            if done:
                break
        return
    
    def select_best_action(self,state):
        x = state
        action = np.argmax(self.q_table[x])
        return action
    
    def play_episode_with_best_policy(self,env):
        state = env.reset()
        ret = 0
        vis(env)
        
        while True:
            action = self.select_best_action(state)
            next_state, reward, done, info = env.step(action)
            
            ret += reward
            state = next_state
            
            vis(env)
            
            if done:
                break
        return ret

In [4]:
env = gym.make('FrozenLake-v0')
agent = Agent()

In [5]:
gamma = 0.9
alpha = 0.5

for k in trange(10000):
    agent.play_episode(env)

100%|██████████| 10000/10000 [00:05<00:00, 1932.24it/s]


In [6]:
print(agent.q_table.argmax(axis=1).reshape(4,4))

[[0 3 0 3]
 [0 0 1 0]
 [3 1 0 0]
 [0 2 2 0]]


In [8]:
sum_ret = 0
for k in range(1000):
    sum_ret += agent.play_episode_with_best_policy(env)

  (Left)
SFFF
FHFH
FFFH
HFFG


KeyboardInterrupt: 

In [ ]:
sum_ret

In [ ]:
env.env.P[10][2]