<br><br>
<font size='6'><b>Dynamic Programming</b></font>

<br>
<div class=pull-right>
By Prof. Seungchul Lee<br>
http://iai.postech.ac.kr/<br>
Industrial AI Lab at POSTECH
</div>

Source

- By Prof. David J. Malan from Harvard University
- By Prof. Erik Demaine from MIT online lecture

Table of Contents
<div id="toc"></div>

# 1. Recursive Algorithm

- one of the central ideas of computer science


- depends on solutions to smaller instances of the same problem ( = subproblem)


- function to call itself (it is impossible in the real world)


- factorial example 
    - $n! = n\cdot(n-1) \cdots 2\cdot 1$

<br>
<img src = "./image_files/recursion01_2.png" width = 450>
<br>

- watch Harvard CS50 lecture on recursion (https://cs50.harvard.edu/)

In [1]:
%%html
<center><iframe width="560" height="315" src="https://www.youtube.com/embed/t4MSwiqfLaY" 
frameborder="0" allowfullscreen></iframe></center>

## 1.1. foo example

In [5]:
print('Hello class')

Hello class


In [1]:
def foo(str):
    print(str)

In [2]:
foo('Hello class')

Hello class


In [3]:
# Do not run. It falls into infinite loop.
def foo_recursion(str):
    print("{}".format(str))
    return foo_recursion(str)

In [4]:
#foo_recursion('Hello Class')
foo_recursion('Hi')

Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi
H

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/home/piai/anaconda3/envs/abc/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-8af2a40d0775>", line 1, in <module>
    foo_recursion('Hi')
  File "<ipython-input-3-0da34a956ecc>", line 3, in foo_recursion
    return foo_recursion(str)
  File "<ipython-input-3-0da34a956ecc>", line 3, in foo_recursion
    return foo_recursion(str)
  File "<ipython-input-3-0da34a956ecc>", line 3, in foo_recursion
    return foo_recursion(str)
  [Previous line repeated 2950 more times]
  File "<ipython-input-3-0da34a956ecc>", line 2, in foo_recursion
    print("{}".format(str))
  File "/home/piai/anaconda3/envs/abc/lib/python3.8/site-packages/ipykernel/iostream.py", line 404, in write
    self.pub_thread.schedule(lambda : self._buffer.write(string))
  File "/home/piai/anaconda3/envs/abc/lib/python3.8/site-packages/ipykernel/iostream.py", line 202, in

TypeError: object of type 'NoneType' has no len()

In [6]:
# more smart function
def foo(n):
    if n <= 0:
        return
    else:
        print("hi")
        foo(n-1)

In [7]:
foo(5)

hi
hi
hi
hi
hi


Hi! 

Hi! 

Hi! 

Hi! 



## 1.2. Factorial example

- factorial example 
    - $n! = n\cdot(n-1) \cdots 2\cdot 1$

In [9]:
# calculate 5! using "for"
n=5

m=1
for i in range(n):
    m = m*(i+1)

print(m)    

120


In [10]:
# Use recursive function
def fac(n):
    if n==1:
        return 1
    else:
        return n*fac(n-1)

In [11]:
fac(5)

120

# 2. Dynamic Programming

- Dynamic Programming: general, powerful algorithm design technique


- Fibonacci numbers:

$$
\begin{align*}
F_1 &= F_2 = 1 \\
F_n &= F_{n-1} + F_{n-2}
\end{align*}
$$


## 2.1. Naive Recursive algorithm

$$
\begin{align*}
\text{fib}(n):&\\
&\text{if } n \leq 2:\; f = 1\\
&\text{else}:\; f = \text{fib}(n-1) + \text{fib}(n-2)\\
&\text{return } f
\end{align*}$$

it  works, Is it good?

<br>
<img src = "./image_files/DP01_2.png" width = 300>
<br>

## 2.2. Memorized DP algorithm
$$
\begin{align*}
\text{memo }= [\;]&\\
\text{fib}(n):&\\
& \text{if $n$ in memo : return memo}[n]\\ \\
& \text{if } n\leq 2 :\; f = 1\\
& \text{else}: \;f = \text{fib}(n-1) + \text{fib}(n-2)\\ \\
&\text{memo}[n] = f\\
&\text{return } f
\end{align*}$$

Benefit?

- fib$(n)$ only recurses the first time it's called
 
<br>
<img src = "./image_files/DP01_2.png" width = 300>
<br>

- memorize (remember) & re-use solutions to subproblems that helps solve the problem.

$\quad \implies$ DP $\simeq$ recursion + memorization

In [12]:
%%html
<center><iframe width="560" height="315"src="https://www.youtube.com/embed/OQ5jsbhAv_M" 
frameborder="0" allowfullscreen></iframe></center>

## 2.3. Examples


### 2.3.1. Fibonacci

In [12]:
# naive Fibonacci

def fib(n):
    if n <= 2:
        return 1
    else:
        return fib(n-1)+fib(n-2)

In [14]:
fib(15)

610

In [28]:
# Memorized DP Fibonacci

def mfib(n):
    global memo
    if memo[n-1] != 0: # 중복계산방지 : 한번 계산했다면 저장된 메모리에있는것을 찾아서 사용
        return memo[n-1]
    
    if n <= 2:
        memo[n-1] = 1
        return memo[n-1]
    else :
        memo[n-1] = mfib(n-1)+mfib(n-2)
        return memo[n-1]

In [29]:
import numpy as np

n = 10
memo = np.zeros(n)
mfib(n)

55.0

In [30]:
memo

array([ 1.,  1.,  2.,  3.,  5.,  8., 13., 21., 34., 55.])

In [31]:
n = 30
%timeit fib(30)

150 ms ± 533 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
memo = np.zeros(n)
%timeit mfib(30)

572 ns ± 7.74 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### 2.3.2. Climbing a stair

You are climbing a stair case. Each time you can either make 1 step, 2 steps, or 3 steps. How many distinct ways can you climb if the stairs has $n = 30$ steps?

In [32]:
def stair(n):
    if n == 1:
        return 1
    elif n == 2:
        return 2
    elif n == 3:
        return 4
    else:
        return stair(n-1) + stair(n-2) + stair(n-3)

In [33]:
stair(5)

13

In [49]:
def mstair(n):
    global memo
    if memo[n] != 0:
        return memo[n]
    
    if n == 1:
        memo[n] = 1
        return memo[n]
    elif n == 2:
        memo[n] = 2
        return memo[n]
    elif n == 3:
        memo[n] = 4
        return memo[n]
    else:
        memo[n] =  mstair(n-1) + mstair(n-2) + mstair(n-3)
        return memo[n]

In [50]:
n = 5 
global memo
memo = np.zeros(n+1)

mstair(n)
print(memo)

[ 0.  1.  2.  4.  7. 13.]


[ 0.  1.  2.  4.  7. 13.]


### 2.3.3. Knapsack problem using Dynamic Programming (DP)

From MIT's [Introduction to Computer Science and Programming](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-00-introduction-to-computer-science-and-programming-fall-2008/)

__Knapsack problem__

- burglar (or thief) can carry at most 20 kg (i.e., maximum capacity = 20)

- Quickly decide which item to carry


| items | 1 | 2 | 3 | 4 | 5 | 6 |
| --- | --- | --- | --- | --- | --- | --- |
| weight | 10 | 9 | 4 | 2 | 1 | 20 |
| value | 175 | 90 | 20 | 50 | 10 | 200 |


**Approach**

1. guess (or trial and error)

2. Exhaustive search if possible

3. "smarter way" $\implies$ Recursive or dynamic programming

$$
\text{key ideas} = \text{original problem} \rightarrow \begin{cases} \text{subproblem} \rightarrow & \begin{cases} \text{subproblem} \rightarrow \\ \text{subproblem} \rightarrow \end{cases}\\ \text{subproblem} \rightarrow & \begin{cases} \text{subproblem} \rightarrow\\ \text{subproblem} \rightarrow\end{cases}\end{cases} 
$$

<br><br>
Suppose we have the following function:

$\quad$`[value, taken] = chooseBest(items(1:6),maxWeight)`

1) item 1 is not taken

$\quad$`[v_1,t_1] = chooseBest(items(2:6),maxWeight)`

   
2) item 1 is taken

$\quad$`[v_2,t_2] = chooseBest(items(2:6),maxWeight - weights(1))`

$\quad\qquad\;\;\,$`v_2 = v_2 + values(1)`

$\qquad\quad\;\;\,$`t_2 = [items(1),t_2]`   

In [47]:
def chooseBest(items,maxWeight):
    global weights
    global values
    
    if len(items) == 0 or maxWeight <= 0:
        value = 0
        taken = []
        return value, taken
    else:
        first = items[0]
        w = weights[first]
        rest = items[1:]
        
        # do not take the first item
        v1,t1 = chooseBest(rest,maxWeight)
        
        # do take the first item
        v2,t2 = chooseBest(rest,maxWeight - w)
        v2 = v2 + values[first]
        t2 = [first] + t2
        
        if maxWeight - w >= 0 and v2 >= v1:
            value = v2
            taken = t2
        else:
            value = v1
            taken = t1
        
        return value, taken              

In [48]:
n = 6
weights = [10, 9, 4, 2, 1, 20]
values = [175, 90, 20, 50, 10, 200]

items = range(n)
maxWeight = 20

chooseBest(items,maxWeight)

(275, [0, 1, 4])

In [24]:
%%javascript
$.getScript('https://kmahelona.github.io/ipython_notebook_goodies/ipython_notebook_toc.js')

<IPython.core.display.Javascript object>