<br><br>
<font size='6'><b>Markov Chain</b></font><br><br>

<br>
<div class=pull-right>
By Prof. Seungchul Lee<br>
http://iai.postech.ac.kr/<br>
Industrial AI Lab at POSTECH
</div>

Table of Contents
<div id="toc"></div>

# 1. Markov Process (or Chain)

## 1.1. Sequential Processes

- Most classifiers ignored the sequential aspects of data


- Consider a system which can occupy one of $N$ discrete states or categories
$q_t \in \{S_1,S_2,\cdots,S_N\}$


- We are interested in stochastic systems, in which state evolution is random


- Any joint distribution can be factored into a series of conditional distributions

<br>
$$p(q_0,q_1,\cdots,q_T ) = p(q_0) \; p(q_1 \mid q_0) \; p( q_2 \mid q_1 q_0 ) \; p( q_3 \mid q_2 q_1 q_0 ) \cdots$$
<br>
<center>Amost impossible to compute !!</center>


<br>
$$p(q_0,q_1,\cdots,q_T ) = p(q_0) \; p(q_1 \mid q_0) \; p( q_2 \mid q_1 ) \; p( q_3 \mid q_2 ) \cdots$$
<br>
<center>Possible and tractable !!</center>

## 1.2. Markov Process


- (Assumption) for a Markov process, the next state depends only on the current state:

<br>

$$ p(q_{t+1} \mid q_t,\cdots,q_0)  = p(q_{t+1} \mid q_t)$$

<br>

- More clearly

<br>

$$ p(q_{t+1} = s_j \mid q_t = s_i)  = p(q_{t+1} = s_j \mid q_t = s_i,\; \text{any earlier history})$$

<br>

- Given current state, the past does not matter
- The state captures all relevant information from the history
- The state is a sufficient statistic of the future


## 1.3. State Transition Matrix

- For a Markov state 𝑠 and successor state 𝑠′, the state transition probability is defined by

<br>

$$ P_{ss'} = P\left[S_{t+1} = s' \mid S_t = s \right] $$

<br>

- State transition matrix $P$ defines transition probabilities from all states $s$ to all successor states $s'$.

<br>
<center><img src = "./image_files/transitionmatrix.png" width = 250></center>
<br>

<br>
<center><img src="./image_files/chain_example.png" width = 600></center>
<br>

Example: Markov chhain episodes

- sample episodes starting from $S_1$

In [121]:
import numpy as np

# Make state transition matrix 

P = [[0, 0, 1],
     [1/2, 1/2, 0],
     [1/3, 2/3, 0]]

In [122]:
print(P[1])

[0.5, 0.5, 0]


In [157]:
a = np.random.choice(3, 1, p = P[1])
#a = np.random.choice(3,1,p = P[1][:])
print(a)

[1]


In [158]:
# sequential processes
# sequence generated by Markov chain
# S1 = 0, S2 = 1, S3 = 2

# starting from 0
x = 0
S = []
S.append(x)

for i in range(50):    
    x = np.random.choice(3,1,p = P[x][:])[0]    
    S.append(x)
     
print(S)    

[0, 2, 1, 0, 2, 1, 1, 1, 0, 2, 0, 2, 1, 0, 2, 0, 2, 1, 1, 0, 2, 0, 2, 1, 0, 2, 1, 1, 1, 0, 2, 1, 0, 2, 0, 2, 0, 2, 1, 0, 2, 1, 1, 1, 1, 1, 0, 2, 1, 1, 0]


## 1.4. Markov Chain Components

It represents passive stochastic behavior

$\;\;$ 1) a finite set of $N$ states, $S = \{ S_1, \cdots , S_N \}$

$\;\;$ 2) a state transition probability, $P = \{ p_{ij} \}_{M \times M},\quad 1 \leq i,j \leq M$

$\;\;$ 3) an initial state probability distribution, $\pi = \{ \pi_i\}$


<br>

Example of Markov Chain

- Starting from $S_1$ = Class 1


<img src = "./image_files/student_MC.png" width = 500>

In [87]:
P = [[0, 0.5, 0, 0, 0, 0.5, 0],
    [0, 0, 0.8, 0, 0, 0, 0.2],
    [0, 0, 0, 0.6, 0.4, 0, 0],
    [0, 0, 0, 0, 0, 0, 1],
    [0.2, 0.4, 0.4, 0, 0, 0, 0],
    [0.1, 0, 0, 0, 0, 0.9, 0],
    [0, 0, 0, 0, 0, 0, 1]]

# sequential processes
# sequence generated by Markov chain
# [C1 C2 C3 Pass Pub FB Sleep] = [0 1 2 3 4 5 6]

name = ['C1','C2','C3','Pass','Pub','FB','Sleep']

# starting from 0
# make 10 sequence

x = 0
S = []
S.append(x)

for i in range(10):    
    x = np.random.choice(7,1,p = P[x][:])[0]    
    S.append(x)
     
print(S)    

[0, 5, 5, 5, 5, 5, 0, 1, 2, 3, 6]


In [88]:
episode = []

for i in S:
    episode.append(name[i])

print(episode)    

['C1', 'FB', 'FB', 'FB', 'FB', 'FB', 'C1', 'C2', 'C3', 'Pass', 'Sleep']


# 2. Chapman-Kolmogorov Equation


- (1-step transition probabilities) For a Markov chain on a finite state space, $S = \{ S_1, \cdots , S_N \}$, with transition probability matrix $P$ and initial distribution $\pi = \{ \pi_i^{0} \}$ (row vector) then the distribution of $X(1)$ is given by

<img src = "./image_files/CKE_01.png" width = 400>

- (2-step transition probabilities) For a Markov chain on a finite state space, $S = \{ S_1, \cdots , S_N \}$, with transition probability matrix $P$ and initial distribution $\pi = \{ \pi_i^{0} \}$ (row vector) then the distribution of $X(2)$ is given by

<br>
<img src = "./image_files/CKE_02.png" width = 500>
<br>

- (n-step transition probabilities) For a Markov chain on a finite state space, $S = \{ S_1, \cdots , S_N \}$, with transition probability matrix $P$ and initial distribution $\pi = \{ \pi_i^{0} \}$ (row vector) then the distribution of $X(n)$ is given by

<br>
<img src = "./image_files/CKE_03.png" width = 500>
<br>

- $P^n$: n-step transition probabilities


- Key recursion

$$p_{ij}(n) = \sum_{k=1}^{N} p_{ik}(n-1) p_{kj}(1), \qquad i \rightarrow k \; \text{and}\; k \rightarrow j \;\text{imply}\; i \rightarrow j$$

<br>
<img src = "./image_files/CKE_diagram.png" width = 400>

<br>
<img src = "./image_files/chain_example.png" width = 600>

In [170]:
# state probability distribution

P = [[0, 0, 1],
    [1/2, 1/2, 0],
    [1/3, 2/3, 0]]

u = [0, 1, 0] # initial 위치 -> S2, 확률로도 표현가능 [1/5, 1/5, 3/5] 합이 1이되야함

P = np.asmatrix(P)
u = np.asmatrix(u)

for i in range(10):
    u = u*P
    print(u) #[S1에 있을 확률 , S2에 있을 확률, S3에 있을 확률]

[[0.5 0.5 0. ]]
[[0.25 0.25 0.5 ]]
[[0.29166667 0.45833333 0.25      ]]
[[0.3125     0.39583333 0.29166667]]
[[0.29513889 0.39236111 0.3125    ]]
[[0.30034722 0.40451389 0.29513889]]
[[0.30063657 0.3990162  0.30034722]]
[[0.29962384 0.39973958 0.30063657]]
[[0.30008198 0.40029417 0.29962384]]
[[0.3000217  0.39989632 0.30008198]]


In [119]:
u = [0, 1, 0]
u = u*P**10
print(u)

[[0.3000217  0.39989632 0.30008198]]


# 3. Stationary Distribution

- Steady-state behavior


- Does $p_{ij}(n)=P[X_n = j \mid X_0 = i] $ converge to some $\pi_j$ ?


- Take the limit as $n \rightarrow \infty$

$$p_{ij}(n) = \sum_{k=1}^{N} p_{ik}(n-1) p_{kj}$$


$$\pi_j = \sum_{k=1}^{N} \pi_k p_{kj}$$


- Need also $\sum_j \pi_j = 1$


$$\pi = \pi P$$


- How to compute (https://brilliant.org/wiki/stationary-distributions/)
    - Eigen-analysis 
    - Fixed-point iteration (we already did)




In [ ]:
'''
lamb * 𝜋 = 𝑃 * 𝜋

𝑃라는 matrix에서 어떤 vector를 곱했을 때 값은 그대로이면서 방향만 변하게되는 vector (eigenvector)
또, 방향은 그대로이면서 크기만 변하게 되는 값 (eigenvalue)
eigenvalue와 eigenvector는 𝑃에 의해서 결정됨.

eigenvalue -> 𝑃
eigenvector -> 𝜋

3 by 3 matrix에서 eigenvector와 eigenvalue는 각각 3개씩 나오게 되는데
아래의 경우 1보다 작은 eigenvalue는 계속 곱하면 0이 되서 없어지므로 1인 eigenvalue만 남게된다.

eigenvalue가 1일때의 eigenvector를 Normalize하여 확률로 표시한다.
(eigenvector는 방향만 있으므로 Normalize해야함.)
'''

In [191]:
# eigenvalue = 1 and associated eigenvector
# lamb * 𝜋 = 𝑃 * 𝜋
d, v = np.linalg.eig(P.T)

# loof for eigenvalue = 1
print(np.real(d)) # eigen value
print()
print(np.real(v)) # eigen vector는 방향만 가지고 있다. 크기가 1로 normalize하면 확률로 표시가 된다.

[-0.25 -0.25  1.  ]

[[ 0.18463724  0.18463724 -0.51449576]
 [ 0.55391171  0.55391171 -0.68599434]
 [-0.73854895 -0.73854895 -0.51449576]]


In [192]:
# get eigenvector of eigenvalue=1 
print(np.real(v[:,2]/sum(v[:,2]))) #eigenvalue로 구한값

[[0.3]
 [0.4]
 [0.3]]


In [11]:
%%javascript
$.getScript('https://kmahelona.github.io/ipython_notebook_goodies/ipython_notebook_toc.js')

<IPython.core.display.Javascript object>