## Gradient Descent

In [2]:
import numpy as np

In [3]:
# 셀자르기 : Ctrl + shift + -
# 셀합치기 : esc -> shift + M
# 지워진 셀 복구 : esc ->  z

H = np.array([[2,0.1],
              [0.2,2]])
g = -np.array([[1,6],
              [1,6]])

H*g

array([[ -2. ,  -0.6],
       [ -0.2, -12. ]])

In [4]:
'''
min {(x1-g1)**2 + (x2-g2)**2}
    x1과 x2에서 거리가 최소가 되는 문제 정의

f = 1/2 * (X.T * H) * X + (g.T * X)
    vector 행렬로 변환

gradient f = HX + g
    미분해서 gradient를 계산하고 반복해서 x가 최소가 되는지점 탐색
'''
H = np.array([[2,0],
              [0,2]])
g = -np.array([[6],
              [6]])

x = np.zeros(shape=(2, 1))
alpha = 0.1

for _ in range(50):
    df = H@x + g
    x = x - alpha * df

print(x)

[[2.99995718]
 [2.99995718]]


In [3]:
H = np.matrix([[2,0],[0,2]])
g = np.matrix([[6],[6]])

x = np.zeros((2,1))
alpha = 0.2

for i in range(25):
    df = H*x + g
    x = x - alpha*df

print(x)

[[-2.99999147]
 [-2.99999147]]


## Linear Programming

In [8]:
'''
Gradient Descent

상한값과 하한값의 제약조건이 있을 때
lb_TF : True(1), False(0)로 반환
ub_TF : True(1), False(0)로 반환
'''

f = -np.array([[3],
               [1.5]])
lb = np.array(([-1],
               [0]))
ub = np.array(([2],
               [3]))

x = np.zeros(shape=(2, 1))
alpha = 0.1

for _ in range(100):
    df = f
    x = x - alpha * df
    
    # lb constraints
    lb_TF = lb < x
    #x = lb_TF * x + lb * np.logical_not(lb_TF)
    x = lb_TF * x + ~lb_TF * lb
    
    # ub constraints
    ub_TF = x < ub
    #x = ub_TF * x + ub * np.logical_not(ub_TF)
    x = ub_TF * x + ~ub_TF * ub

print(x)

[[2.]
 [3.]]


In [5]:
f = np.array([[-3],
              [-3/2]])

x = np.zeros((2,1))
alpha = 0.2

lb = np.array(([-1],[0]))
ub = np.array(([2],[3]))

for i in range(25):
    x = x - alpha * f
    
    # lb constraints
    lb_TF = lb < x
    x = x * lb_TF.astype(int) + lb * np.logical_not(lb_TF).astype(int)

    # ub constraints
    ub_TF = x < ub
    x = x * ub_TF.astype(int) + ub * np.logical_not(ub_TF).astype(int)

print(x)

[[2.]
 [3.]]


In [11]:
import cvxpy as cvx

In [9]:
'''
Gradient Descent

cvxpy를 이용해서 계산
'''

f = np.array([[3],
              [3/2]])
lb = np.array([[-1],
               [0]])
ub = np.array([[2],
               [3]])

x = cvx.Variable([2, 1])

obj = cvx.Minimize(-f.T @ x)
constraints = [lb <= x, x <= ub]

prob = cvx.Problem(obj, constraints)
prob.solve()

-10.499999966365493

In [33]:
#import cvxpy as cvx

f = np.array([[3],[3/2]])
lb = np.array([[-1],[0]])
ub = np.array([[2],[3]])

x = cvx.Variable([2, 1])

obj = cvx.Minimize(-f.T*x)
constraints = [lb <= x, x <= ub]

prob = cvx.Problem(obj, constraints)
result = prob.solve()

print(x.value)
print(result)

[[1.99999999]
 [2.99999999]]
-10.499999966365493


/home/piai/anaconda3/lib/python3.8/site-packages/cvxpy/expressions/expression.py:556: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 12 times so far.

  warnings.warn(msg, UserWarning)


## Quadratic Programming

In [15]:
f = np.array([[3],[4]])
H = np.array([[1/2, 0],[0, 0]])

A = np.array([[-1, -3], [2, 5], [3, 4]])
b = np.array([[-15], [100], [80]])
lb = np.array([[0], [0]])

x = cvx.Variable([2, 1])

obj = cvx.Minimize(cvx.quad_form(x, H) + f.T@x)
constraints = [A@x <= b, lb <= x]

prob = cvx.Problem(obj, constraints)
result = prob.solve()
print(x.value)
print(result)

[[-1.15591357e-25]
 [ 5.00000000e+00]]
20.000000000000004


## Empty Bucket

In [9]:
'''
min {norm((a-x),2) + norm((b-x),2)}
'''

a = np.array([[0],[1]])
b = np.array([[4],[2]])

x_const = np.array([[0, 1]])

x = cvx.Variable([2, 1])
mu = 1.0

obj = cvx.Minimize(cvx.norm(a-x, 2) + mu * cvx.norm(b-x, 2))
#constraints = [x_const @ x == 0]
constraints = [x_const @ x <= 0, 0 <= x_const @ x]

prob = cvx.Problem(obj, constraints)
result = prob.solve()

print(x.value)
print(result)

[[1.33338655e+00]
 [1.77600856e-10]]
5.000000000245686


In [73]:
a = np.array([[0],[1]])
b = np.array([[4],[2]])

x_const = np.array([[1, 0],[0, 0]])

x = cvx.Variable([2, 1])
mu = 1.0

obj = cvx.Minimize(cvx.norm(a-x_const@x, 2) + mu * cvx.norm(b-x_const@x, 2))
constraints = []

prob = cvx.Problem(obj, constraints)
result = prob.solve()

print(x.value)
print(result)

[[1.33344196]
 [0.        ]]
5.000000001911563
