# Linear Algebra

## Linear Equations

In [1]:
import numpy as np

In [2]:
A = np.array([[4,-5],
              [-2,3]])
b = np.array([[-13],
                [9]])

In [3]:
print(A)

[[ 4 -5]
 [-2  3]]


In [4]:
print(b)

[[-13]
 [  9]]


In [5]:
x = np.linalg.inv(A).dot(b)
# x = np.linalg.inv(A) @ b
print(x)

[[3.]
 [5.]]


In [6]:
A = np.asmatrix(A)
B = np.asmatrix(b)

x = A.I*B
print(x)

[[3.]
 [5.]]


## Vector-Vector Products

In [7]:
x = np.array([[1],
              [1]]) # (2, 1) -> (1, 2)

y = np.array([[2],
              [3]])

In [8]:
print(x.T.dot(y))

[[5]]


In [10]:
x = np.asmatrix(x)
y = np.asmatrix(y)

print(x.T*y)

[[5]]


## Norms (strenth or distance in linear space)

In [11]:
x = np.array([[4],
              [3]])

np.linalg.norm(x,2)

5.0

In [12]:
np.linalg.norm(x,1)

7.0

## Orthogonal Projection onto a Subspace

In [17]:
import numpy as np

A = np.matrix([[1,0],
               [0,1],
               [0,0]])
B = np.matrix([[2],
               [2],
               [2]])

In [18]:
X_star = (A.T*A).I*A.T*B

In [19]:
print(X_star)

[[2.]
 [2.]]


In [20]:
A * X_star

matrix([[2.],
        [2.],
        [0.]])